name: recomsys_onlyNN
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=1.3.0=py39haa95532_0
  - aiohttp=3.8.3=py39h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py39haa95532_0
  - attrs=22.1.0=py39haa95532_0
  - blas=1.0=mkl
  - blinker=1.4=py39haa95532_0
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2022.10.11=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - cryptography=38.0.4=py39h21b164f_0
  - fftw=3.3.9=h2bbff1b_1
  - flatbuffers=2.0.0=h6c2663c_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - frozenlist=1.3.3=py39h2bbff1b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h62dcd97_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.42.0=py39hc60d5dd_0
  - h5py=3.7.0=py39h3de5c98_0
  - hdf5=1.10.6=h1756f20_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py39haa95532_0
  - importlib-metadata=4.11.3=py39haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9e=h2bbff1b_0
  - keras=2.10.0=py39haa95532_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - libcurl=7.86.0=h86230a5_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.1=h23ce68f_0
  - libssh2=1.10.0=hcd4344a_0
  - markdown=3.4.1=py39haa95532_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - multidict=6.0.2=py39h2bbff1b_0
  - oauthlib=3.2.1=py39haa95532_0
  - openssl=1.1.1s=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=22.0=py39haa95532_0
  - pip=22.3.1=py39haa95532_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39haa95532_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.15=h6244533_2
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - requests=2.28.1=py39haa95532_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.9.3=py39he11b74f_0
  - setuptools=65.6.3=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h6c2663c_0
  - sqlite=3.40.1=h2bbff1b_0
  - tensorboard=2.10.0=py39haa95532_0
  - tensorboard-data-server=0.6.1=py39haa95532_0
  - tensorboard-plugin-wit=1.8.1=py39haa95532_0
  - tensorflow=2.10.0=mkl_py39ha510bab_0
  - tensorflow-base=2.10.0=mkl_py39h6a7f48e_0
  - tensorflow-estimator=2.10.0=py39haa95532_0
  - termcolor=2.1.0=py39haa95532_0
  - typing_extensions=4.4.0=py39haa95532_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.13=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - werkzeug=2.2.2=py39haa95532_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - wrapt=1.14.1=py39h2bbff1b_0
  - yarl=1.8.1=py39h2bbff1b_0
  - zipp=3.11.0=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - libclang==13.0.0
      - numpy==1.24.1
      - protobuf==3.19.0
      - tensorflow-io-gcs-filesystem==0.23.1
prefix: C:\Users\sorana\.conda\envs\recomsys_onlyNN
